version: "3.8"
services:
    traefik:
        image: traefik:2.6
        restart: always
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - /traefik:/etc/traefik
            - /var/run/docker.sock:/var/run/docker.sock:ro
    ExampleBackend:
        image: example-backend
        restart: always
        ports:
            -   10000
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.ExampleBackend.rule=(Host(`yourServerAddress.com`)'
            - 'traefik.http.routers.ExampleBackend.tls=true'
            - 'traefik.http.routers.ExampleBackend.tls.certresolver=lets-encrypt'
            - 'traefik.http.routers.ExampleBackend.service=svc_ExampleBackend'
            - 'traefik.http.services.svc_ExampleBackend.loadbalancer.server.port=10000'